app/urls.py
from .views import Home, ProfileList, ProfileCreate,Watch,ShowMovieDetail,ShowMovie
from django.urls import path

app_name='app'

urlpatterns = [
    path('',Home.as_view()),
    path('profile/',ProfileList.as_view(),name='profile_list'),
    path('profile/create/',ProfileCreate.as_view(),name='profile_create'),
    path('watch/<str:profile_id>/',Watch.as_view(),name='watch'),
    path('movie/detail/<str:movie_id>/',ShowMovieDetail.as_view(),name='show_det'),
    path('movie/play/<str:movie_id>/',ShowMovie.as_view(),name='play')
]

netflix/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls',namespace='app')),
    path('accounts/', include('allauth.urls')),
] 
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid
from cloudinary.models import CloudinaryField

AGE_CHOICES=(
    ('All','All'),
    ('Kids','Kids')
)

MOVIE_TYPE=(
    ('single','Single'),
    ('seasonal','Seasonal')
)

class CustomUser(AbstractUser):
    profiles=models.ManyToManyField('Profile')


class Profile(models.Model):
    name=models.CharField(max_length=225)
    age_limit=models.CharField(max_length=5,choices=AGE_CHOICES)
    uuid=models.UUIDField(default=uuid.uuid4,unique=True)


    def __str__(self):
        return self.name +" "+self.age_limit

class Movie(models.Model):
    title:str=models.CharField(max_length=225)
    description:str=models.TextField()
    created =models.DateTimeField(auto_now_add=True)
    uuid=models.UUIDField(default=uuid.uuid4,unique=True)
    type=models.CharField(max_length=10,choices=MOVIE_TYPE)
    videos=models.ManyToManyField('Video')
    flyer=CloudinaryField('image')
    age_limit=models.CharField(max_length=5,choices=AGE_CHOICES,blank=True,null=True)

    def __str__(self) -> str:
        return self.title

class Video(models.Model):
    title:str = models.CharField(max_length=225,blank=True,null=True)
    file=models.FileField(upload_to='movies')

    def __str__(self) -> str:
        return self.title
    
    

    

app/forms.py
from .models import Profile
from django.forms import ModelForm

class ProfileForm(ModelForm):
    class Meta:
        model=Profile
        exclude=['uuid']

app/views.py
from django.shortcuts import redirect, render
from django.views import View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .forms import ProfileForm
from .models import Movie, Profile

class Home(View):
    def get(self,request,*args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to='/profile/')
        return render(request,'index.html')

@method_decorator(login_required,name='dispatch')
class ProfileList(View):
    
    def get(self,request,*args, **kwargs):

        profiles=request.user.profiles.all()

        print(profiles)


        return render(request,'profileList.html',{
            'profiles':profiles
        })


@method_decorator(login_required,name='dispatch')
class ProfileCreate(View):
    def get(self,request,*args, **kwargs):
        form=ProfileForm()

        return render(request,'profileCreate.html',{
            'form':form
        })

    def post(self,request,*args, **kwargs):
        form=ProfileForm(request.POST or None)

       
        if form.is_valid():
            print(form.cleaned_data)
            profile = Profile.objects.create(**form.cleaned_data)
            if profile:
                request.user.profiles.add(profile)
                return redirect(f'/watch/{profile.uuid}')

        return render(request,'profileCreate.html',{
            'form':form
        })

@method_decorator(login_required,name='dispatch')
class Watch(View):
    def get(self,request,profile_id,*args, **kwargs):
        try:
            profile=Profile.objects.get(uuid=profile_id)

            movies=Movie.objects.filter(age_limit=profile.age_limit)
            

            try:
                showcase=movies[0]
            except :
                showcase=None
            

            if profile not in request.user.profiles.all():
                return redirect(to='app:profile_list')
            
        
            return render(request,'movieList.html',{
            'movies':movies,
            'show_case':showcase,
            'bg':[x for x in movies]
            })
        except Profile.DoesNotExist:
            return redirect(to='app:profile_list')


@method_decorator(login_required,name='dispatch')
class ShowMovieDetail(View):
    def get(self,request,movie_id,*args, **kwargs):
        try:
            
            movie=Movie.objects.get(uuid=movie_id)

            return render(request,'movieDetail.html',{
                'movie':movie
            })
        except Movie.DoesNotExist:
            return redirect('app:profile_list')

@method_decorator(login_required,name='dispatch')
class ShowMovie(View):
    def get(self,request,movie_id,*args, **kwargs):
        try:
            
            movie=Movie.objects.get(uuid=movie_id)

            movie=movie.videos.values()
            

            return render(request,'showMovie.html',{
                'movie':list(movie)
            })
        except Movie.DoesNotExist:
            return redirect('app:profile_list')

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        
        {% endblock title %}
    </title>
    <link rel="stylesheet" href="{% static 'style.css' %} ">
    {% block others %}
    
    {% endblock others %}
</head>
<body class='bg-black text-gray-100 font-primary'>

    {% block content %}

    {% endblock content %}

    <script>
        const nav = document.querySelector('nav')

        document.addEventListener("scroll",e=>{
            
            if(scrollY>100){
                nav.classList.add('bg-gray-900')
          
            }else{
                nav.classList.remove('bg-gray-900')
                
            }
        })

    </script>
    
</body>
</html>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix</title>
    <link rel="stylesheet"   href="{% static 'main.css' %} ">
</head>
<body>
    <header class="showcase">
        <div class="showcase-top">
            <img src="https://i.ibb.co/r5krrdz/logo.png" alt="" />
            {% if AUTH != 'false'  %}
            {% if request.user.is_authenticated %}
            <div>
            <form action="{% url 'account_logout' %}" method="post">
                {% csrf_token %}
                <button class="btn btn-rounded">
                    Logout
                </button>
            </form>
            </div>
            {% else %}
            <div>
            <a class="btn btn-rounded" href="{% url 'account_login' %}">

                
                    Sign In 
                
            </a>
            </div>
            {% endif %}
        {% endif %}
        </div>
        <div class="showcase-content">
            <h1>See what's next</h1>
            <p>Watch anywhere. Cancel Anytime</p>
            <a href="#" class="btn btn-xl"
                >Watch Free For 30 Days <i class="fas fa-chevron-right btn-icon"></i
            ></a>
        </div>
    </header>
    <section class="tabs">
        <div class="container">
            <div id="tab-1" class="tab-item tab-border">
                <i class="fas fa-door-open fa-3x"></i>
                <p class="hide-sm">Cancel at any time</p>
            </div>
            <div id="tab-2" class="tab-item">
                <i class="fas fa-tablet-alt fa-3x"></i>
                <p class="hide-sm">Watch anywhere</p>
            </div>
            <div id="tab-3" class="tab-item">
                <i class="fas fa-tags fa-3x"></i>
                <p class="hide-sm">Pick your price</p>
            </div>
        </div>
    </section>

    <section class="tab-content">
        <div class="container">
            <!-- Tab Content 1 -->
            <div id="tab-1-content" class="tab-content-item show">
                <div class="tab-1-content-inner">
                    <div>
                        <p class="text-lg">
                            If you decide Netflix isn't for you - no problem. No commitment.
                            Cancel online anytime.
                        </p>
                        <a href="#" class="btn btn-lg">Watch Free For 30 Days</a>
                    </div>
                    <img src="https://i.ibb.co/J2xDJV7/tab-content-1.png" alt="" />
                </div>
            </div>

            <!-- Tab Content 2 -->
            <div id="tab-2-content" class="tab-content-item">
                <div class="tab-2-content-top">
                    <p class="text-lg">
                        Watch TV shows and movies anytime, anywhere — personalized for
                        you.
                    </p>
                    <a href="#" class="btn btn-lg">Watch Free For 30 Days</a>
                </div>
                <div class="tab-2-content-bottom">
                    <div>
                        <img src="https://i.ibb.co/DpdN7Gn/tab-content-2-1.png" alt="" />
                        <p class="text-md">
                            Watch on your TV
                        </p>
                        <p class="text-dark">
                            Smart TVs, PlayStation, Xbox, Chromecast, Apple TV, Blu-ray
                            players and more.
                        </p>
                    </div>
                    <div>
                        <img src="https://i.ibb.co/R3r1SPX/tab-content-2-2.png" alt="" />
                        <p class="text-md">
                            Watch instantly or download for later
                        </p>
                        <p class="text-dark">
                            Available on phone and tablet, wherever you go.
                        </p>
                    </div>
                    <div>
                        <img src="https://i.ibb.co/gDhnwWn/tab-content-2-3.png" alt="" />
                        <p class="text-md">
                            Use any computer
                        </p>
                        <p class="text-dark">
                            Watch right on Netflix.com.
                        </p>
                    </div>
                </div>
            </div>

            <!-- Tab Content 3 -->
            <div id="tab-3-content" class="tab-content-item">
                <div class="text-center">
                    <p class="text-lg">
                        Choose one plan and watch everything on Netflix.
                    </p>
                    <a href="#" class="btn btn-lg">Watch Free For 30 Days</a>
                </div>

                <table class="table">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Basic</th>
                            <th>Standard</th>
                            <th>Premium</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Monthly price after free month ends on 6/19/19</td>
                            <td>$8.99</td>
                            <td>$12.99</td>
                            <td>$15.99</td>
                        </tr>
                        <tr>
                            <td>HD Available</td>
                            <td><i class="fas fa-times"></i></td>
                            <td><i class="fas fa-check"></i></td>
                            <td><i class="fas fa-check"></i></td>
                        </tr>
                        <tr>
                            <td>Ultra HD Available</td>
                            <td><i class="fas fa-times"></i></td>
                            <td><i class="fas fa-times"></i></td>
                            <td><i class="fas fa-check"></i></td>
                        </tr>
                        <tr>
                            <td>Screens you can watch on at the same time</td>
                            <td>1</td>
                            <td>2</td>
                            <td>4</td>
                        </tr>
                        <tr>
                            <td>Watch on your laptop, TV, phone and tablet</td>
                            <td><i class="fas fa-check"></i></td>
                            <td><i class="fas fa-check"></i></td>
                            <td><i class="fas fa-check"></i></td>
                        </tr>
                        <tr>
                            <td>Unlimited movies and TV shows</td>
                            <td><i class="fas fa-check"></i></td>
                            <td><i class="fas fa-check"></i></td>
                            <td><i class="fas fa-check"></i></td>
                        </tr>
                        <tr>
                            <td>Cancel anytime</td>
                            <td><i class="fas fa-check"></i></td>
                            <td><i class="fas fa-check"></i></td>
                            <td><i class="fas fa-check"></i></td>
                        </tr>
                        <tr>
                            <td>First month free</td>
                            <td><i class="fas fa-check"></i></td>
                            <td><i class="fas fa-check"></i></td>
                            <td><i class="fas fa-check"></i></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </section>

    <footer class="footer">
        <p>Questions? Call 1-866-579-7172</p>
        <div class="footer-cols">
            <ul>
                <li><a href="#">FAQ</a></li>
                <li><a href="#">Investor Relations</a></li>
                <li><a href="#">Ways To Watch</a></li>
                <li><a href="#">Corporate Information</a></li>
                <li><a href="#">Netflix Originals</a></li>
            </ul>
            <ul>
                <li><a href="#">Help Center</a></li>
                <li><a href="#">Jobs</a></li>
                <li><a href="#">Terms Of Use</a></li>
                <li><a href="#">Contact Us</a></li>
            </ul>
            <ul>
                <li><a href="#">Account</a></li>
                <li><a href="#">Redeem Gift Cards</a></li>
                <li><a href="#">Privacy</a></li>
                <li><a href="#">Speed Test</a></li>
            </ul>
            <ul>
                <li><a href="#">Media Center</a></li>
                <li><a href="#">Buy Gift Cards</a></li>
                <li><a href="#">Cookie Preferences</a></li>
                <li><a href="#">Legal Notices</a></li>
            </ul>
        </div>

    </footer>
</body>
</html>

<script src="{% static 'net.js' %}"></script>

templates/movieDetail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Detail Page
{% endblock title %}

{% block others %}

<script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>
{% endblock others %}

{% block content %}

    {% include 'partials/navbar.html' %}
    <main class='bg-primary_black min-h-screen w-full'>
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex  items-end bg-cover" style="background-image: url('{{movie.flyer.url}}');">
            <div>
                <h2 class="text-6xl font-semibold text-white my-4">
                    {{movie.title}}
                </h2>
                <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                    {{movie.description |slice:":50"}}...
                    {% lorem 1 %}
                </p>
                <div class="flex my-4">
                    <a href="{% url 'app:play' movie_id=movie.uuid %}">
                    
                        <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                            <ion-icon name="play" class="text-2xl"></ion-icon>
                            <span class="ml-3 font-medium">
                                Play
                            </span>
                        </button>
                    </a>
    
                    
                </div>
            </div>
        </section> 
        <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                {% if movie.type == 'seasonal' %}
                <div style='margin-top:2rem;margin-bottom:2rem;'>
                
                    <h2 class="text-gray-200 text-3xl font-medium">
                        Episode
                    </h2>
                    {% for episode in movie.videos.all %}
                        <h3 class='text-lg'>
                            <a href="{% url 'app:play' movie_id=movie.uuid %}?epi={{forloop.counter0}}">
                            
                            {{forloop.counter}} - {{episode.title}}
                            </a>
                        </h3>
                    {% endfor %}
                
                </div>
                {% endif %}

                <h2 class="text-gray-200 text-3xl font-medium">
                    Description
                </h2>
                <div class="flex justify-center  items-center min-w-full  movie_lis">
                    <p class="text-gray-100 text-lg">
                        
                        {{movie.description}}    
                    </p>
                </div>
            </div>
        </section>
        
    </main>
    
{% endblock content %}

templates/movieList.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Netflix 
{% endblock title %}

{% block others %}
    <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>

{% endblock others %}
{% block content %}


    {% include 'partials/navbar.html' %}
    <main class='bg-primary_black min-h-screen w-full'>
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex  items-end bg-cover" style="background-image:url('{{show_case.flyer.url}}') ">
            <div>
                <h2 class="text-6xl font-semibold text-white my-4">
                    {{show_case.title}}
                </h2>
                <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                    {{show_case.description | slice:":300"}}...
                    
                </p>
                <div class="flex my-4">
                    <a href="{% url 'app:play' movie_id=show_case.uuid %}">
                    
                        <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                            <ion-icon name="play" class="text-2xl"></ion-icon>
                            <span class="ml-3 font-medium " >
                                Play
                            </span>
                        </button>
                    </a>

                    <a href="{% url 'app:show_det' movie_id=show_case.uuid %}">
                        <button class="ml-4 text-white flex items-center bg-gray-500 bg-opacity-80 py-2 px-5 rounded-md">
                        
                            <ion-icon name="information-circle-outline" class="text-2xl" ></ion-icon>
                            <span class="ml-3 font-medium">
                                More Info
                            </span>
                        </button>
                    
                    </a>
    
                </div>
            </div>
        </section> 
        <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Popular on Netflix
                </h2>
                <div class="flex   items-center min-w-full  movie_lis">
                    {% for movie in movies %}
                    
                        <a href="{% url 'app:show_det' movie_id=movie.uuid %}">
                            <div class=" h-40 m-4  bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer w-40">
                                <img src="{{movie.flyer.url}}" class="w-full h-full " alt="">
                            </div>
                        
                        </a>
                    {% endfor %}

                   

                
                </div>
            </div>
        </section>
        
    </main>
{% endblock content %}

templates/partials/navbar.html
{% load static %}
<nav class="flex text-gray-100 justify-between items-center py-3 px-4 fixed w-full z-50">
        <div class="w-6/12">
            <a href='/'>
            
            <img src="{% static 'netflix.png' %}" alt="logo" class="w-5/12 md:w-2/12">
            </a>
        </div>

        {% if AUTH != 'false'  %}
            {% if request.user.is_authenticated %}
            <div>
            <form action="{% url 'account_logout' %}" method="post">
                {% csrf_token %}
                <button class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                    Logout
                </button>
            </form>
            </div>
            {% else %}
            <div>
            <a href="{% url 'account_login' %}">

                <button class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                    Sign In 
                </button>
            </a>
            </div>
            {% endif %}
        {% endif %}
    </nav>

templates/profileCreate.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Netflix - Profile
{% endblock title %}

{% block content %}
    {% include 'partials/navbar.html' %}
    <section class='bg-primary_black min-h-screen py-20 md:py-32 flex-col flex items-center' style='background-image:url("{% static 'background_netflix.jpg' %}")'>
        <div class="flex flex-wrap justify-center  w-10/12  md:w-6/12">
            <form method='POST' class="w-full md:w-8/12 bg-gray-900 p-5 rounded-lg">
                {% if request.user.profiles.all|length > 5 %}
                    <p class='text-center text-xl'>

                        Sorry, you can't create any Profiles because you have exceeded the limit
                        
                    </p>
                {% else %}
                
                    <h1 class="text-4xl text-center text-gray-100 font-medium">
                        Create A Profile
                    </h1>
                    {% csrf_token %}
                
                    {{form.errors}}
                    <div class="my-4"> 
                        <Label class='text-lg text-gray-200 font-medium mb-3'>
                            Profile Name
                        </Label>
                        <input required class="p-2 bg-gray-500 rounded-sm text-gray-200 outline-none block w-full" type="text" name="name" id="id_name" placeholder="Profile name">
                    </div>
                    <div class="my-4"> 
                        <Label class='text-lg text-gray-200 font-medium mb-3'>
                            Maturity Level
                        </Label>
                        <select class="p-2 bg-gray-500 rounded-sm text-gray-200 outline-none block w-full"  name="age_limit" id="id_age_limit" >
                            <option value="All">All</option>
                            <option value="Kids">Kids</option>
                        
                        </select>
                    </div>
                    <div class="flex justify-center items-center">
                        <button class="px-4 py-2 rounded-md outline-none bg-primary_red text-gray-100">Create Profile</button>
                    </div>
                {% endif %}
            </form> 
        </div>
        
    </section>

{% endblock content %}

templates/profileList.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Netflix - Profile
{% endblock title %}

{% block content %}
    {% include 'partials/navbar.html' %}



    <section class='bg-primary_black min-h-screen py-20 md:py-0 flex-col flex justify-center items-center'>
        <h2 class="text-center font-medium text-5xl my-4 text-gray-100">
            Who's watching ?
        </h2>

        <div class="flex flex-wrap justify-center items-center w-10/12  md:w-6/12">

        {% for profile in profiles %}
            <a href="{% url 'app:watch' profile_id=profile.uuid %}">
            
                <div class="w-32 h-32 m-4  bg-blue-500 flex justify-center items-center flex-col rounded-md cursor-pointer">
                    <p class='text-6xl'>
                        {{profile.name | slice:":1"}}
                    </p>
                    <p class='text-lg'>
                        {{profile.name}}
                    </p>
                </div>
            </a>
        {% endfor %}

        </div>
        {% if request.user.profiles.all|length < 5 %}
      
            <div class="flex justify-center items-center">
                <a href="{% url 'app:profile_create' %}">
                    
                    <button class="px-4 py-2 rounded-md outline-none bg-gray-400 text-gray-100">
                        Add A New Profile
                    </button>
                </a>
            </div>
        {% endif %}
    </section>
{% endblock content %}

templates/showMovie.html
{% extends 'base.html' %}

{% block title %}
Netflix - Movie
{% endblock title %}

{% block content %}

    {% include 'partials/navbar.html' %}
    <main class='bg-primary_black h-full w-full '>

        {{ movie|json_script:"movie_data" }}
        
        <video  controls class="w-full h-screen player"></video>
        
    </main>
    <script>
        const videoEl=document.querySelector('video')
        const movie_data = JSON.parse(document.getElementById('movie_data').textContent);
        
       
        const url =new URL(location.href)
        
        const video_param = parseInt(url.searchParams.get("epi")) ? parseInt(url.searchParams.get("epi")) : 0

        videoEl.setAttribute('src',`https://netflix-pjt.herokuapp.com/media/${movie_data[video_param].file}`)
    </script>
{% endblock content %}